name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - name: Build binaries
        run: |
          # Linux builds
          GOOS=linux GOARCH=amd64 go build -v -o dist/unzip-takeout-linux-amd64
          GOOS=linux GOARCH=arm64 go build -v -o dist/unzip-takeout-linux-arm64

          # macOS builds
          GOOS=darwin GOARCH=amd64 go build -v -o dist/unzip-takeout-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -v -o dist/unzip-takeout-darwin-arm64

          # Windows build
          GOOS=windows GOARCH=amd64 go build -v -o dist/unzip-takeout-windows-amd64.exe

      - name: Generate checksums
        run: |
          cd dist
          sha256sum * > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/unzip-takeout-linux-amd64
            dist/unzip-takeout-linux-arm64
            dist/unzip-takeout-darwin-amd64
            dist/unzip-takeout-darwin-arm64
            dist/unzip-takeout-windows-amd64.exe
            dist/checksums.txt
          generate_release_notes: true
